version: '3.8'

services:
  ai_assistant_dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    image: ai_assistant:dev
    container_name: ai_assistant_dev
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ..:/app  # Mount the entire project for development
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - CONFIG_PATH=/app/configs/environments/development.yaml
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - redis
      - postgres
      - vector_db
    networks:
      - ai_network_dev
    command: python -m src.main --config ${CONFIG_PATH}

  redis:
    image: redis:7-alpine
    container_name: ai_assistant_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ai_network_dev

  postgres:
    image: postgres:15-alpine
    container_name: ai_assistant_postgres_dev
    restart: unless-stopped
    environment:
      - POSTGRES_USER=ai_assistant
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=ai_assistant_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - ai_network_dev

  vector_db:
    image: qdrant/qdrant:latest
    container_name: ai_assistant_vector_db_dev
    restart: unless-stopped
    ports:
      - "6333:6333"
    networks:
      - ai_network_dev

networks:
  ai_network_dev:
    driver: bridge

volumes:
  postgres_data_dev:
