apiVersion: v1
kind: Service
metadata:
  name: ai-assistant-api-service
  namespace: ai-assistant
spec:
  selector:
    app: ai-assistant-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer