# Note Taker Configuration
# Configuration for the voice-based note taking skill

note_taker:
  # Audio settings
  audio:
    format: "wav"  # Audio format: wav, flac
    quality: "high"  # Audio quality: low, medium, high
    auto_enhance: true  # Apply audio enhancement

  # Processing settings
  processing:
    auto_summarize: true  # Automatically create summaries
    detect_action_items: true  # Extract action items
    extract_definitions: true  # Extract definitions and key concepts
    categorize_content: true  # Automatically categorize notes

  # Export settings
  export:
    default_format: "markdown"  # Default export format
    include_audio_links: true  # Include audio file references
    timestamp_format: "iso"  # Timestamp format: iso, readable
    export_directory: "data/notes/exports"  # Export directory

  # Storage settings
  storage:
    notes_directory: "data/notes"  # Base notes directory
    audio_directory: "data/notes/audio"  # Audio files directory
    temp_directory: "/tmp/note_taker"  # Temporary files directory
    use_date_folders: true  # Organize by date folders
    max_file_size_mb: 100  # Maximum audio file size

  # Integration settings
  integrations:
    logseq:
      enabled: false  # Enable Logseq integration
      auto_export: false  # Automatically export to Logseq
      pages_directory: "data/notes/exports/logseq"  # Logseq pages directory
    
    appflowy:
      enabled: false  # Enable AppFlowy integration
      workspace_path: "data/notes/exports/appflowy"  # AppFlowy workspace path
    
    joplin:
      enabled: false  # Enable Joplin integration
      notebook_path: "data/notes/exports/joplin"  # Joplin notebook path

  # Summarizer settings
  summarizer:
    max_summary_length: 200  # Maximum summary length in characters
    max_key_points: 5  # Maximum number of key points to extract
    min_sentence_length: 10  # Minimum sentence length for processing
    use_llm: true  # Use LLM for summarization when available
    fallback_to_extractive: true  # Fall back to extractive summarization

  # Content analyzer settings
  analyzer:
    min_confidence: 0.7  # Minimum confidence for automatic categorization
    max_action_items: 10  # Maximum action items to extract
    max_definitions: 10  # Maximum definitions to extract
    max_tags: 15  # Maximum tags to generate