# Time-Block Efficiency Planner Skill Configuration

time_block_planner:
  # General settings
  enabled: true
  language_primary: "ar"  # Arabic first
  language_secondary: "en"  # English fallback
  
  # Time blocking preferences
  default_block_length: 90  # minutes
  max_deep_work_blocks: 3
  preferred_break_length: 15  # minutes
  buffer_time_percentage: 0.1  # 10% buffer time
  
  # Work schedule defaults
  default_work_hours:
    start: "09:00"
    end: "17:00"
    
  # Focus optimization
  focus_peak_hours:
    - "09:00-11:00"  # Morning peak
    - "14:00-16:00"  # Afternoon peak
    
  # Disruption handling
  disruption_detection: true
  auto_adjust_schedule: true
  reminder_interval: 5  # minutes before each block
  
  # Task classification
  task_parsing:
    arabic_keywords_enabled: true
    auto_priority_detection: true
    duration_extraction: true
    focus_type_detection: true
    
  # Integration settings
  integrations:
    calendar_sync: true
    text_to_speech: true
    memory_persistence: true
    
  # Performance tracking
  analytics:
    track_completion_rates: true
    learn_user_patterns: true
    optimize_future_schedules: true