# Context Time Machine Skill Configuration
# Author: Drmusab
# Last Modified: 2025-01-08

time_machine:
  # General settings
  enabled: true
  version: "1.0.0"
  
  # Language settings
  default_language: "ar"  # Arabic as primary language
  supported_languages: ["ar", "en"]
  bilingual_mode: true
  
  # Search configuration
  search:
    max_results: 50
    min_relevance_threshold: 0.3
    snippet_length: 200
    default_search_mode: "hybrid"  # semantic, keyword, hybrid, temporal, contextual
    
  # Memory replay configuration
  replay:
    max_threads: 10
    max_segment_gap_seconds: 300  # 5 minutes
    min_thread_duration_seconds: 60  # 1 minute
    default_replay_mode: "summary"  # full, summary, highlights, timeline, contextual
    max_summary_length: 500
    
  # Behavioral analysis configuration
  analysis:
    min_data_points: 3
    trend_sensitivity: 0.1
    confidence_threshold: 0.6
    
    # Behavioral metrics to track
    metrics:
      - "tone"
      - "mood" 
      - "energy"
      - "confidence"
      - "engagement"
      - "complexity"
    
  # Visualization configuration
  visualization:
    enabled: true
    default_chart_type: "line_chart"  # line_chart, bar_chart, area_chart, scatter_plot, radar_chart
    default_export_format: "json"  # json, csv, svg, ascii
    chart_width: 800
    chart_height: 400
    
    # Chart colors for metrics
    colors:
      tone: "#e74c3c"
      mood: "#f39c12"
      energy: "#e67e22"
      confidence: "#27ae60"
      engagement: "#3498db"
      formality: "#9b59b6"
      complexity: "#34495e"
      responsiveness: "#1abc9c"
  
  # Query processing configuration
  query_processing:
    max_processing_time_seconds: 30
    enable_caching: true
    cache_ttl_seconds: 300  # 5 minutes
    
  # Pattern matching configuration
  patterns:
    # Time reference patterns (for Arabic and English)
    time_patterns:
      arabic:
        last_week: ["الأسبوع الماضي", "الأسبوع اللي فات", "آخر أسبوع"]
        last_month: ["الشهر الماضي", "الشهر اللي فات", "آخر شهر"]
        yesterday: ["أمس", "البارحة", "يوم أمس"]
        recently: ["مؤخراً", "في الآونة الأخيرة", "منذ فترة قريبة"]
      english:
        last_week: ["last week", "previous week", "a week ago"]
        last_month: ["last month", "previous month", "a month ago"]
        yesterday: ["yesterday", "last day"]
        recently: ["recently", "lately", "not long ago"]
    
    # Query type patterns
    query_types:
      conversation_recall:
        arabic: ["ماذا تحدثنا", "عن ماذا تكلمنا", "ما الذي ناقشناه"]
        english: ["what did we talk about", "what did we discuss", "conversation topics"]
      
      project_mention:
        arabic: ["متى.*ذكرت", "آخر مرة.*المشروع", "متى تحدثت عن"]
        english: ["when.*mentioned", "last time.*project", "when did.*talk about"]
      
      behavioral_analysis:
        arabic: ["هل تحسن.*أسلوبي", "كيف.*سلوكي", "تحليل سلوكي"]
        english: ["have I improved", "how.*behavior", "behavioral analysis"]
    
    # Behavioral indicators
    behavioral_patterns:
      tone:
        positive:
          arabic: ["ممتاز", "رائع", "جيد", "شكراً", "أحب", "سعيد"]
          english: ["excellent", "great", "good", "thank", "love", "happy"]
        negative:
          arabic: ["سيء", "لا أحب", "مشكلة", "صعب", "مستحيل"]
          english: ["bad", "hate", "problem", "difficult", "impossible"]
      
      confidence:
        high:
          arabic: ["أعتقد", "متأكد", "بالتأكيد", "لا شك", "واثق"]
          english: ["i think", "sure", "definitely", "certainly", "confident"]
        low:
          arabic: ["لست متأكد", "ربما", "لا أعرف", "صعب"]
          english: ["not sure", "maybe", "don't know", "difficult"]
      
      energy:
        high:
          arabic: ["متحمس", "نشيط", "سريع", "فوراً", "بسرعة"]
          english: ["excited", "energetic", "quick", "immediately", "fast"]
        low:
          arabic: ["متعب", "مرهق", "بطيء", "لاحقاً"]
          english: ["tired", "exhausted", "slow", "later"]
  
  # Integration settings
  integration:
    # Memory system integration
    memory:
      search_all_types: true
      prioritize_episodic: true
      include_working_memory: false
    
    # Event system integration
    events:
      emit_skill_events: true
      emit_analysis_events: true
      emit_visualization_events: false
    
    # Bilingual system integration
    bilingual:
      auto_detect_language: true
      preserve_original_language: true
      translate_insights: false
  
  # Logging and debugging
  logging:
    level: "INFO"  # DEBUG, INFO, WARNING, ERROR
    log_queries: true
    log_results: false
    log_performance: true
  
  # Performance settings
  performance:
    enable_async_processing: true
    max_concurrent_searches: 3
    enable_result_caching: true
    cache_search_results: true
    cache_analysis_results: true